[package]
name = "ebell"
version = "0.1.0"
authors = ["Gary Davies <gary.l.davies@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.36"
enigo = "0.2.0-rc2"
